service: ner-api


provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-1

package:
 exclude:
   - node_modules/**
   - .vscode/**
   - __pycache__/**
   - .ipynb_checkpoints/**
   - (*).ipynb


functions:
  recognize-named-entites:
    handler: handler.handle_request
    memorySize: 1536
    timeout: 30
    events: 
      - http: 
          path: ner
          method: post
          
  recognize-named-tag:
    handler: handler.recognize_named_tag
    memorySize: 1536
    timeout: 30
    events: 
      - http: 
          path: tag
          method: post


plugins:
  - serverless-python-requirements

custom: 
  pythonRequirements:
    dockerizePip: non-linux
    # pythonBin: python
    # slim: true
    zip: true
    # noDeploy: []
    # useDownloadCache: true
    # useStaticCache: true